language: python

python:
  - "3.6"
  - "3.7"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-ci.txt"

script:
   - snekchek
   - echo "No tests for now"

cache: pip

notifications:
  email: false
