FORMAT: 1A
HOST: https://sayonika.moe/api/v1

# Velvet API

This is the official documentation for the Sayonika Project/Velvet.

We worked very hard on the documentation, so if you find any errors, let us know in the [GitHub Repository](https://github.com/Sayo-nika/Backend).


## Mods [/mods/{mod_id}]


### GET

Lists all mods - paginated into 100 entries per request.

+ Response 200 (application/json)

        {
            "total": 420,
            "page": 2,
            "limit": 10,
            "results": [Mod, Mod, ...]
        }

### POST

Adds a new entry in the database, requires authentication.


+ Request (application/json)
    + Headers

            Authorization: Token <Insert your token here>
    + Body

            {
               "title": "",
               "category": 2,
               "download_url": "",
               "..."
            }

+ Response 200 

+ Response 400 (text/plain)

        Illegal input. It may be the title was taken or you have a badly formatted resquest.

+ Response 403 (text/plain)

        Unauthorized.
        
### PATCH [/mods/{mod_id}]

+ Parameters
    + mod_id (Snowflake<Number>) - ID of the Mod in the form of a number. Leave it empty if you don't have a specific mod to search.


Updates the entry in the database. Keep in mind `mod_id` is important for this request to be acknowledged.


+ Request (application/json)
    + Headers

            Authorization: Token <Insert your token here>
    + Body

            {
               "title": "",
               "category": 2,
               "download_url": "",
               "..."
            }

+ Response 200 

+ Response 400 (text/plain)

        Illegal input. It may be you didn't specify a Mod ID or your request format is badly done.

+ Response 403 (text/plain)

        Unauthorized.
        

    


## Users [/users]


### GET

Lists all user - paginated into 100 entries per request.

+ Response 200 (application/json)

        {
            "total": 420,
            "page": 2,
            "limit": 10,
            "results": [User, User, ...]
        }