FORMAT: 1A
HOST: https://sayonika.moe/api/v1

# Velvet API

This is the official documentation for the Sayonika Project/Velvet.

We worked very hard on the documentation, so if you find any errors, let us know in the [GitHub Repository](https://github.com/Sayo-nika/Backend).

Keep in mind we won't document parts of API that consumers should not touch, so if you are a author that wants to use this backend, refer to the in-code documentation.


## Mods [/mods]


### GET

Lists all mods - paginated into 100 entries per request.

+ Response 200 (application/json)

        {
            "total": 420,
            "page": 2,
            "limit": 10,
            "results": [Mod, Mod, ...]
        }




## Mod Specific [/mods/{mod_id}]

+ Parameters
    + mod_id (Snowflake<Number>) - ID of the Mod in the form of a number. Leave it empty if you don't have a specific mod to search.


### GET

Gets info from the mod.

+ Response 200 (application/json)

            {
               "title": "",
               "category": 2,
               "download_url": "",
               "..."
            }
        

## Users [/users]


### GET

Lists all user - paginated into 100 entries per request.

+ Response 200 (application/json)

        {
            "total": 420,
            "page": 2,
            "limit": 10,
            "results": [User, User, ...]
        }

## User Specific [/user/{user_id}]

+ Parameters
    + user_id (Snowflake<Number>) - ID of the Mod in the form of a number. Leave it empty if you don't have a specific mod to search.


### GET

Gets info of user.

+ Response 200 (application/json)

            {
               "username": "",
               "bio": 2,
               "connections": [Connection, Connection, ...],
               ...
            }